# Clean_null_datatype

: **전처리 과정으로, 데이터의 nan값을 적당한 변수로 바꾸어주고 datatype을 정리해줍니다**

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from glob import glob
import warnings

In [2]:
os.chdir('c:\\Users\\user\\Desktop\\Growth Hackers\\dacon_know\\data_0103')

In [3]:
warnings.filterwarnings(action='ignore') 
pd.options.display.max_columns=None
know_train = [pd.read_csv(path) for path in sorted(glob('./train/*.csv'))]
know_test = [pd.read_csv(path) for path in sorted(glob('./test/*.csv'))]

# Data Overview
- insight
    * 연도별로 train/ test 모두 칼럼 수가 다르다(마스터 테이블을 만들기 어렵다는 문제)
    * 공백으로 NaN 값이 표현되고 있다 (Null값에 대한 문제)
    * text로 답변한 문항이 있다 (object를 어떻게 처리할 것인지에 대한 문제)
    * 숫자인데 object로 기록된 문항들이 무척 많다 (데이터 타입 문제)

In [4]:
print(know_train[0].shape)
know_train[0].head(2) # 2017년도 train

(9486, 156)

,idx,aq1_1,aq1_2,aq2_1,aq2_2,aq3_1,aq3_2,aq4_1,aq4_2,aq5_1,aq5_2,aq6_1,aq6_2,aq7_1,aq7_2,aq8_1,aq8_2,aq9_1,aq9_2,aq10_1,aq10_2,aq11_1,aq11_2,aq12_1,aq12_2,aq13_1,aq13_2,aq14_1,aq14_2,aq15_1,aq15_2,aq16_1,aq16_2,aq17_1,aq17_2,aq18_1,aq18_2,aq19_1,aq19_2,aq20_1,aq20_2,aq21_1,aq21_2,aq22_1,aq22_2,aq23_1,aq23_2,aq24_1,aq24_2,aq25_1,aq25_2,aq26_1,aq26_2,aq27_1,aq27_2,aq28_1,aq28_2,aq29_1,aq29_2,aq30_1,aq30_2,aq31_1,aq31_2,aq32_1,aq32_2,aq33_1,aq33_2,aq34_1,aq34_2,aq35_1,aq35_2,aq36_1,aq36_2,aq37_1,aq37_2,aq38_1,aq38_2,aq39_1,aq39_2,aq40_1,aq40_2,aq41_1,aq41_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15_1,bq15_2,bq15_3,bq16,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq19,bq19_1,bq20,bq21,bq22,bq23,bq24_1,bq24_2,bq24_3,bq24_4,bq24_5,bq24_6,bq24_7,bq24_8,bq25,bq26,bq27,bq28,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq38,bq38_1,bq39_1,bq39_2,bq40,bq41_1,bq41_2,bq41_3,knowcode
0,0,3,3,3,3,3,3,4,4,3,4,3,3,2,2,2,2,2,2,3,3,3,3,4,4,3,3,3,2,3,3,5,6,5,6,4,5,2,2,5,6,3,4,4,5,3,4,4,4,2,2,3,4,4,5,3,4,1,,2,2,3,3,1,,2,2,2,5,3,4,3,4,2,2,2,2,5,2,2,2,2,2,3,1,6,1,자동차도장기능사,,,1,2,실무교육,5,2,4,3,3,4,4,3,4,3,4,4,4,4,3,2,4,3,2,2,4,4,2,3,2,3,3,2,생산설비의 자동화로,2,3,5,10.0,1,1,1,2,2,2,2,2,3,3,4,3,2,없다,없다,없다,건설현장 노무직,없다,4,1,52,2,실업,1,1,1,4000,,2200,825101
1,1,4,5,4,5,3,4,3,4,3,4,1,,1,,1,,1,,2,3,3,4,3,4,4,5,2,2,3,4,3,4,3,4,3,4,1,,2,3,1,,3,4,3,4,2,3,1,,3,4,2,3,3,4,1,,1,,3,4,1,,3,4,3,4,1,,3,4,3,4,3,4,2,2,1,,1,,13,1,3,1,건축전기설비기술사,,,2,,,6,5,4,3,3,4,4,2,3,3,4,4,3,3,3,2,3,3,4,3,4,2,2,4,2,2,4,2,건설 수주가 없어서,3,3,6,50.0,2,2,2,2,2,2,2,2,4,3,4,3,2,없다,"매타기, 드라이버, 가위, CAD",,,,2,1,38,4,건축공학,1,1,1,,,2400,140204

In [5]:
print(know_test[0].shape)
know_test[0].head(2) # 2017년도 test

(9486, 155)

,idx,aq1_1,aq1_2,aq2_1,aq2_2,aq3_1,aq3_2,aq4_1,aq4_2,aq5_1,aq5_2,aq6_1,aq6_2,aq7_1,aq7_2,aq8_1,aq8_2,aq9_1,aq9_2,aq10_1,aq10_2,aq11_1,aq11_2,aq12_1,aq12_2,aq13_1,aq13_2,aq14_1,aq14_2,aq15_1,aq15_2,aq16_1,aq16_2,aq17_1,aq17_2,aq18_1,aq18_2,aq19_1,aq19_2,aq20_1,aq20_2,aq21_1,aq21_2,aq22_1,aq22_2,aq23_1,aq23_2,aq24_1,aq24_2,aq25_1,aq25_2,aq26_1,aq26_2,aq27_1,aq27_2,aq28_1,aq28_2,aq29_1,aq29_2,aq30_1,aq30_2,aq31_1,aq31_2,aq32_1,aq32_2,aq33_1,aq33_2,aq34_1,aq34_2,aq35_1,aq35_2,aq36_1,aq36_2,aq37_1,aq37_2,aq38_1,aq38_2,aq39_1,aq39_2,aq40_1,aq40_2,aq41_1,aq41_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15_1,bq15_2,bq15_3,bq16,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq19,bq19_1,bq20,bq21,bq22,bq23,bq24_1,bq24_2,bq24_3,bq24_4,bq24_5,bq24_6,bq24_7,bq24_8,bq25,bq26,bq27,bq28,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq38,bq38_1,bq39_1,bq39_2,bq40,bq41_1,bq41_2,bq41_3
0,0,3,4,2,2,3,3,1,,3,5,1,,3,4,3,4,3,3,4,5,2,2,2,3,2,3,4,6,4,6,1,,1,,1,,4,5,1,,1,,1,,1,,4,5,3,4,4,6,4,5,3,4,2,2,2,3,3,4,4,5,1,,2,2,1,,1,,1,,2,2,4,5,1,,1,,13,2,6,2,,,,2,,,7,4,4,3,3,2,3,4,4,4,3,3,4,3,3,2,2,2,2,1,2,2,3,4,3,2,3,3,다른것으로 대체할 수 없는 업무,2,3,1,0.0,2,2,2,2,2,2,2,2,3,4,3,2,1,없다,컴퓨터,없다,없다,없다,2,2,26,3,비서학,1,1,1,3000,,2300
1,1,5,5,3,5,5,5,5,5,4,5,4,5,5,5,5,5,4,6,4,5,4,5,4,4,4,5,4,5,4,5,4,6,5,6,4,5,5,4,5,4,1,,5,3,2,3,3,4,3,4,4,3,4,4,4,3,3,4,3,4,4,4,3,4,3,4,3,4,4,5,4,4,4,4,4,4,4,4,1,,4,5,3,1,4,1,품질관리기사,,,1,1,실무교육,5,4,4,3,3,4,4,3,3,3,3,3,3,4,4,3,4,3,4,3,3,3,2,4,3,4,4,2,제조업이 줄어들 것으로 생각되기 때문,2,2,4,30.0,2,2,2,2,2,2,2,2,4,5,4,3,1,없다,"제품검사시스템,PC,엑셀",없다,없다,,3,1,57,4,농화학,1,1,1,5500,,2500

In [6]:
print(know_train[1].shape)
know_train[1].head(2) # 2018년도 train

(9072, 141)

,idx,cq1,cq2,cq3,cq4,cq5,cq6,cq7,cq8,cq9,cq10,cq11,cq12,cq13,cq14,cq15,cq16,cq17,cq18,cq19,cq20,cq21,cq22,cq23,cq24,cq25,cq26,cq27,cq28,cq29,cq30,cq31,cq32,cq33,cq34,cq35,cq36,cq37,cq38,cq39,cq40,cq41,cq42,cq43,cq44,cq45,cq46,cq47,cq48,cq49,cq50_1,cq50_2,cq50_3,cq50_4,cq50_5,cq50_6,cq50_7,cq50_8,iq1,iq2,iq3,iq4,iq5,iq6,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15,bq16,bq17,bq18,bq19,bq20,bq21,bq221,bq222,bq223,bq231,bq232,bq233,bq234,bq235,bq241,bq242,bq243,bq244,bq245,bq25,bq25_1,bq26_1,bq26_1a,bq26_2,bq26_2a,bq26_3,bq26_3a,bq26_4,bq26_4a,bq27,bq28,bq28_1,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq37_1,bq38,bq38_1,bq38_2,bq39,bq40,bq41_1,bq41_2,bq41_3,knowcode
0,9486,5,3,4,2,2,5,4,5,4,4,4,3,3,4,1,5,3,4.0,2.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,4.0,2.0,1.0,1.0,2.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,4.0,3.0,5.0,4.0,3.0,2.0,3.0,1.0,2.0,1,치과기공사,,,1,3,"세라믹, 지르크니아 등 제작 방법, 프로그램 사용방법",7.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4,4,4,4,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,4.0,70,1,,0,1,0.0,0.0,0,,1,,,,,2,,1,2,1,2,1,1,1,1,2.0,4,정교한 직업 요구의 증가,치기공사,치카공,,교정전문가,,3.0,1.0,27.0,3,치기공과,1,1,,1,42,3800,3400,,306301
1,9487,4,3,4,4,4,4,4,4,4,3,3,3,3,4,3,2,2,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,2.0,1.0,1.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,3.0,2.0,1.0,3.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,4.0,3.0,2.0,2.0,3.0,4.0,10.0,1.0,2.0,1,정보처리기사,,,1,5,"게임 개발 독학, 네트워크 기본 지식",7.0,2.0,3.0,4.0,3.0,4.0,5.0,3.0,3,,5,5,5.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,100,1,,0,1,0.0,0.0,0,,,,3,,,1,2,3,,3,,3,,3,,1.0,2,게임 산업의 축소로 인해,없다,"서브라임텍스트, 유니티, 리눅스",정보보호컨설턴트,일반 프로그래머,없다,3.0,1.0,28.0,2,이과,1,2,,1,40,2300,1800,,133204

In [7]:
print(know_test[1].shape)
know_test[1].head(2) # 2018년도 test

(9069, 140)

,idx,cq1,cq2,cq3,cq4,cq5,cq6,cq7,cq8,cq9,cq10,cq11,cq12,cq13,cq14,cq15,cq16,cq17,cq18,cq19,cq20,cq21,cq22,cq23,cq24,cq25,cq26,cq27,cq28,cq29,cq30,cq31,cq32,cq33,cq34,cq35,cq36,cq37,cq38,cq39,cq40,cq41,cq42,cq43,cq44,cq45,cq46,cq47,cq48,cq49,cq50_1,cq50_2,cq50_3,cq50_4,cq50_5,cq50_6,cq50_7,cq50_8,iq1,iq2,iq3,iq4,iq5,iq6,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15,bq16,bq17,bq18,bq19,bq20,bq21,bq221,bq222,bq223,bq231,bq232,bq233,bq234,bq235,bq241,bq242,bq243,bq244,bq245,bq25,bq25_1,bq26_1,bq26_1a,bq26_2,bq26_2a,bq26_3,bq26_3a,bq26_4,bq26_4a,bq27,bq28,bq28_1,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq37_1,bq38,bq38_1,bq38_2,bq39,bq40,bq41_1,bq41_2,bq41_3
0,9486,4,1,3,1,1,3,2,3,1,1,1,1,2,1,5,1,3.0,1,4.0,4.0,1.0,1.0,4.0,1.0,1.0,1.0,4,4.0,1.0,1.0,5.0,5.0,5,4.0,4.0,4.0,1.0,1.0,4.0,1.0,3.0,4.0,4.0,4.0,5.0,1.0,2.0,1.0,4.0,1.0,1,1,1,1,1.0,1.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,2,,,,2,,,7,1,3.0,2.0,2.0,4.0,2.0,2.0,3.0,3,3,,3.0,3.0,2.0,4.0,1.0,3.0,3.0,3.0,4.0,0.0,,2,0,,2.0,0.0,0,,,,,,5,3,,2,,2.0,,2,,2,,2.0,1,힘든직업이라 일할사람 없음,,"잠수복, 망태",,,,4.0,2,60.0,1,,2,,6,,35.0,,,2000
1,9487,5,4,5,5,5,5,3,3,3,1,2,3,3,5,2,1,4.0,4,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1,1.0,5.0,1.0,1.0,1.0,1,5.0,1.0,3.0,4.0,3.0,3.0,2.0,3.0,3.0,2.0,1.0,3.0,5.0,1.0,2.0,1.0,2.0,3,2,1,1,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,10.0,3.0,2.0,2,,,,1,3,최신 디자인 트렌드 탐색 등,4,4,3.0,3.0,3.0,2.0,4.0,2.0,2.0,3,1,3,3.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,4.0,0.0,1,,0,1,0.0,0.0,0,,1,,,,,1,2,1,2,1.0,2,1,2,3,,1.0,2,"인공지능의 발달, 플랫폼화 되어가는 웹, 쉬워지는 그래픽 프로그램으로 인해서 비전...","디자이너님, 등",웹코딩 프로그램(노트패드)_그래픽툴(포토샵/일러스트레이터/인디자인/어도비 XD/스케...,,같은 범주 안에 있는 직업.,"단순 그래픽을 디자인 하는 것이 아니라, 큰 틀을 디자인하는 UX 디자인이 대세인듯...",2.0,2,26.0,4,커뮤니케이션 디자인 전공,1,1,,1,65.0,2700,2200,

In [8]:
print(know_train[2].shape)
know_train[2].head(2) # 2019년도 train

(8555, 153)

,idx,sq1,sq2,sq3,sq4,sq5,sq6,sq7,sq8,sq9,sq10,sq11,sq12,sq13,sq14,sq15,sq16,kq1_1,kq1_2,kq2_1,kq2_2,kq3_1,kq3_2,kq4_1,kq4_2,kq5_1,kq5_2,kq6_1,kq6_2,kq7_1,kq7_2,kq8_1,kq8_2,kq9_1,kq9_2,kq10_1,kq10_2,kq11_1,kq11_2,kq12_1,kq12_2,kq13_1,kq13_2,kq14_1,kq14_2,kq15_1,kq15_2,kq16_1,kq16_2,kq17_1,kq17_2,kq18_1,kq18_2,kq19_1,kq19_2,kq20_1,kq20_2,kq21_1,kq21_2,kq22_1,kq22_2,kq23_1,kq23_2,kq24_1,kq24_2,kq25_1,kq25_2,kq26_1,kq26_2,kq27_1,kq27_2,kq28_1,kq28_2,kq29_1,kq29_2,kq30_1,kq30_2,kq31_1,kq31_2,kq32_1,kq32_2,kq33_1,kq33_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq22,bq23,bq24,bq25,bq26,bq27,bq27_1,bq28,bq28_1,bq28_2,bq29,bq30,bq31_1,bq31_2,bq31_3,knowcode
0,18569,4,4,4,3,4,4,4,4,4,4,4,5,4,4,4,4,3,3,2,2,1,0,2,2,2,2,3,4,4,5,1,0,4,5,4,5,4,5,4,5,5,6,4,5,4,5,3,4,1,0,1,0,2,2,4,5,3,3,2,2,1,0,2,2,3,4,3,4,2,2,2,2,5,6,4,5,4,5,4,5,5,5,15,2,4,1,전기철도자격증,전동차정비원,,1,5,전동차 내부 익히기,7,4,4,4,3,4,4,4,5,5,4,4,4,4.0,3,4.0,5.0,5.0,5.0,4,5.0,4.0,4.0,4.0,4.0,3.0,4.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,사람은 줄고 일은 많으니까 업무가 많다,3.0,4,수송수요가 늘어날다,4.0,4.0,3,,,,1,35.0,4,기계공학과,1.0,1,,1,40,3500,3000,,812301
1,18570,4,3,4,4,4,4,3,4,5,4,3,5,4,4,1,2,4,6,3,4,4,5,5,5,3,4,5,6,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,4,4,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,4,4,8,1,3,2,,,,2,,,1,4,4,3,3,4,4,3,4,9,9,4,4,1.0,4,3.0,4.0,5.0,3.0,4,3.0,3.0,4.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,,1.0,3,운송시장이 큰 변화 없을듯해서,2.0,3.0,3,"컨테이너 대여사업,랜탈사업",,,1,63.0,3,경영학,2.0,,5,,40.0,,,5000,15201

In [9]:
print(know_test[2].shape)
know_test[2].head(2) # 2019년도 test

(8554, 152)

,idx,sq1,sq2,sq3,sq4,sq5,sq6,sq7,sq8,sq9,sq10,sq11,sq12,sq13,sq14,sq15,sq16,kq1_1,kq1_2,kq2_1,kq2_2,kq3_1,kq3_2,kq4_1,kq4_2,kq5_1,kq5_2,kq6_1,kq6_2,kq7_1,kq7_2,kq8_1,kq8_2,kq9_1,kq9_2,kq10_1,kq10_2,kq11_1,kq11_2,kq12_1,kq12_2,kq13_1,kq13_2,kq14_1,kq14_2,kq15_1,kq15_2,kq16_1,kq16_2,kq17_1,kq17_2,kq18_1,kq18_2,kq19_1,kq19_2,kq20_1,kq20_2,kq21_1,kq21_2,kq22_1,kq22_2,kq23_1,kq23_2,kq24_1,kq24_2,kq25_1,kq25_2,kq26_1,kq26_2,kq27_1,kq27_2,kq28_1,kq28_2,kq29_1,kq29_2,kq30_1,kq30_2,kq31_1,kq31_2,kq32_1,kq32_2,kq33_1,kq33_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq22,bq23,bq24,bq25,bq26,bq27,bq27_1,bq28,bq28_1,bq28_2,bq29,bq30,bq31_1,bq31_2,bq31_3
0,18569,5,5,5,4,4,5,4,5,5,4,5,4,4,4,3,4,2,1,2,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,2,1,1,0,1,0,1,0,2,2,2,3,2,2,1,0,3,4,2,2,1,0,1,0,1,0,1,0,1,0,1,0,2,2,1,0,1,0,1,0,1,0,15,2,4,1,응급구조사 1급,응급구조사 2급,,2,,,5,4,3,3,3,3,3,3,3,3,3,3,3,2.0,3,3.0,3.0,4.0,4.0,4,3.0,3.0,3.0,3.0,2.0,3.0,3.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,,1,4,생명과 관련된 일이므로,2,2.0,2,사무직,,,1,57,4,경영,1,1,,1,45,6700,3800,
1,18570,2,3,3,1,3,2,3,3,3,2,3,4,3,2,1,3,1,0,1,0,1,0,1,0,1,0,1,0,3,3,1,0,1,0,1,0,1,0,1,0,4,4,1,0,3,4,4,4,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,3,1,0,1,0,1,0,1,0,3,1,2,2,,,,2,,,7,2,3,1,2,2,3,2,3,3,4,4,3,4.0,2,2.0,3.0,4.0,4.0,5,2.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,,2,3,3D업종이라서,2,2.0,2,,,,1,27,3,화학,1,1,,1,44,2700,2500,

In [10]:
print(know_train[3].shape)
know_train[3].head(2) # 2020년도 train

(8122, 185)

,idx,saq1_1,saq1_2,saq2_1,saq2_2,saq3_1,saq3_2,saq4_1,saq4_2,saq5_1,saq5_2,saq6_1,saq6_2,saq7_1,saq7_2,saq8_1,saq8_2,saq9_1,saq9_2,saq10_1,saq10_2,saq11_1,saq11_2,saq12_1,saq12_2,saq13_1,saq13_2,saq14_1,saq14_2,saq15_1,saq15_2,saq16_1,saq16_2,saq17_1,saq17_2,saq18_1,saq18_2,saq19_1,saq19_2,saq20_1,saq20_2,saq21_1,saq21_2,saq22_1,saq22_2,saq23_1,saq23_2,saq24_1,saq24_2,saq25_1,saq25_2,saq26_1,saq26_2,saq27_1,saq27_2,saq28_1,saq28_2,saq29_1,saq29_2,saq30_1,saq30_2,saq31_1,saq31_2,saq32_1,saq32_2,saq33_1,saq33_2,saq34_1,saq34_2,saq35_1,saq35_2,saq36_1,saq36_2,saq37_1,saq37_2,saq38_1,saq38_2,saq39_1,saq39_2,saq40_1,saq40_2,saq41_1,saq41_2,saq42_1,saq42_2,saq43_1,saq43_2,saq44_1,saq44_2,vq1,vq2,vq3,vq4,vq5,vq6,vq7,vq8,vq9,vq10,vq11,vq12,vq13,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq14_6,bq14_7,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq16_6,bq16_7,bq16_8,bq16_9,bq16_10,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq21_4,bq22_1,bq22_2,bq22_3,bq22_4,bq22_5,bq22_6,bq23_1,bq23_2,bq23_3,bq24,bq25,bq26,bq26_1,bq27_1,bq27_2,bq28,bq29,bq30_1,bq30_2,bq30_3,knowcode
0,27127,4,4,4,4,4,5,4,5,3,3,4,5,1,,4,5,3,4,1,,3,4,3,4,4,5,3,4,4,5,3,4,3,4,1,,1,,4,5,3,3,3,4,4,4,1,,4,5,1,,1,,1,,5,5,1,,3,4,4,5,1,,3,4,3,4,3,4,1,,3,4,3,3,2,3,2,3,3,4,4,5,3,4,2,4,5,3,4,4,4,4,4,3,4,5,4,16,5,3,1,보건교사 자격증,간호사 자격증,,2,,,7,5,4,4,4,4,4,4,3,3,4,4,4,1,5,5,4,5,5,5,3,3,1,3,4,4,5,4,5,4,4,4,3,4,4,2,2,2,2,2,2,2,2,2,,1,3,일정하게 인원이 정해져 있으므로 일자리 변화는 없을 것 같아서,3,2,3,2,5,7,4,5,2,3,3,4,3,2,42,4,간호학,1,1,1,40,4000,2600,,304003
1,27128,5,6,5,6,4,5,4,5,4,5,4,5,5,6,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4,5,4,5,3,4,4,5,4,5,4,5,4,5,3,4,3,4,4,5,3,3,2,3,2,2,2,2,2,2,3,4,2,2,3,4,3,3,3,3,3,4,3,4,3,3,4,5,4,5,4,4,4,5,4,4,4,4,3,4,4,3,4,4,4,3,4,4,4,15,2,2,1,법무사,,,1,4,현장 업무,4,5,4,4,4,4,4,4,5,5,5,4,4,2,5,4,3,4,4,3,4,4,4,3,4,3,3,4,4,4,4,4,3,4,3,2,2,2,2,2,2,2,2,2,,1,2,경기 침체,3,3,3,2,3,4,3,5,6,6,3,6,5,1,45,4,기계공학,1,1,1,40,4000,3000,,221401

In [11]:
print(know_test[3].shape)
know_test[3].head(2) # 2020년도 test

(8122, 184)

,idx,saq1_1,saq1_2,saq2_1,saq2_2,saq3_1,saq3_2,saq4_1,saq4_2,saq5_1,saq5_2,saq6_1,saq6_2,saq7_1,saq7_2,saq8_1,saq8_2,saq9_1,saq9_2,saq10_1,saq10_2,saq11_1,saq11_2,saq12_1,saq12_2,saq13_1,saq13_2,saq14_1,saq14_2,saq15_1,saq15_2,saq16_1,saq16_2,saq17_1,saq17_2,saq18_1,saq18_2,saq19_1,saq19_2,saq20_1,saq20_2,saq21_1,saq21_2,saq22_1,saq22_2,saq23_1,saq23_2,saq24_1,saq24_2,saq25_1,saq25_2,saq26_1,saq26_2,saq27_1,saq27_2,saq28_1,saq28_2,saq29_1,saq29_2,saq30_1,saq30_2,saq31_1,saq31_2,saq32_1,saq32_2,saq33_1,saq33_2,saq34_1,saq34_2,saq35_1,saq35_2,saq36_1,saq36_2,saq37_1,saq37_2,saq38_1,saq38_2,saq39_1,saq39_2,saq40_1,saq40_2,saq41_1,saq41_2,saq42_1,saq42_2,saq43_1,saq43_2,saq44_1,saq44_2,vq1,vq2,vq3,vq4,vq5,vq6,vq7,vq8,vq9,vq10,vq11,vq12,vq13,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq14_6,bq14_7,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq16_6,bq16_7,bq16_8,bq16_9,bq16_10,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq21_4,bq22_1,bq22_2,bq22_3,bq22_4,bq22_5,bq22_6,bq23_1,bq23_2,bq23_3,bq24,bq25,bq26,bq26_1,bq27_1,bq27_2,bq28,bq29,bq30_1,bq30_2,bq30_3
0,27127,3,4,3,4,4,5,1,,1,,1,,2,3,1,,3,5,1,,1,,1,,3,4,3,5,5,5,4,2,1,,1,,4,5,4,3,4,4,4,2,4,2,1,,1,,3,5,1,,1,,1,,1,,2,5,1,,1,,1,,1,,1,,1,,4,5,3,5,4,4,3,4,4,5,4,5,4,5,4,4,4,4,3,4,4,4,3,4,3,4,4,17,1,3,1,간호조무사 자격증,,,1,4,환자 대응과 의료기기 소독,4,2,4,5,4,4,4,4,2,3,4,4,3,1,4,4,5,4,3,4,5,4,5,2,5,4,5,4,5,4,5,4,5,4,5,2,2,2,2,2,2,2,2,2,,2,4,고령화로 간호 필요한 사람 증가,3,3,3,2,8,7,9,3,4,3,7,9,8,2,27,2,문과,1,1,1,40,2300,2000,
1,27128,4,5,4,5,4,5,3,4,4,6,4,5,3,3,3,4,4,4,4,5,3,4,3,5,5,5,4,5,4,5,4,6,4,5,4,5,4,4,3,6,3,4,4,4,4,6,3,4,2,4,5,6,1,,2,5,1,,1,,4,5,1,,3,4,2,4,3,4,1,,3,5,1,,1,,2,4,3,4,3,5,3,4,3,4,5,3,3,4,4,3,4,3,4,4,5,4,3,17,1,1,1,한약사자격증,,,2,,,6,5,5,4,4,4,4,4,5,9,9,9,4,2,4,4,4,4,4,3,2,4,3,4,3,4,4,3,4,4,4,3,4,3,3,2,2,2,2,2,2,2,2,2,,1,3,4차산업에 별영향을 못받는 직업이라서,3,3,3,2,5,5,5,4,5,5,5,4,5,1,58,4,한약학,2,5,1,40,,,5800

# Null 값에 대하여
 - 공백을 0으로 바꿔서 채워줍시다
 - 존재하는 nan값 역시도 0으로 바꿔서 채워줍시다

In [12]:
# 연도별로 텍스트로 명시된 문항

years = ['2017','2018','2019','2020']

text_2017_question = ['bq4_1a','bq4_1b','bq4_1c','bq5_2','bq19_1','bq30','bq31','bq32','bq33','bq34','bq38_1']
text_2018_question = ['bq4_1a','bq4_1b','bq4_1c','bq5_2','bq28_1','bq29','bq30','bq31','bq32','bq33','bq37_1']
text_2019_question = ['bq4_1a','bq4_1b','bq4_1c','bq5_2','bq18_10','bq20_1','bq22','bq23','bq24','bq27_1']
text_2020_question = ['bq4_1a','bq4_1b','bq4_1c','bq5_2','bq18_10','bq20_1','bq26_1']
whole_list = [text_2017_question, text_2018_question, text_2019_question, text_2020_question]

text_dict = {}
for year, lst in zip(years, whole_list):
    text_dict[year] = lst

In [13]:
# train set에 대하여 공백이 아닌 null 값이 존재함 : 확인해보자

null_train_dict = {}
for year, df in zip(years, know_train):
    null_sum = df.isnull().sum()
    null_train_dict[year] = list(null_sum[null_sum!=0].index)    
    print(year,'의 null 합계 :',null_sum.sum())
    print()

# null 값이 나타난 문항들
print(null_train_dict)

2017 의 null 합계 : 0

2018 의 null 합계 : 37

2019 의 null 합계 : 130

2020 의 null 합계 : 1

{'2017': [], '2018': ['bq40', 'bq41_1', 'bq41_2', 'bq41_3'], '2019': ['bq13_1', 'bq13_2', 'bq13_3', 'bq14_1', 'bq14_2', 'bq14_3', 'bq14_4', 'bq14_5', 'bq15', 'bq16_1', 'bq16_2', 'bq16_3', 'bq16_4', 'bq16_5', 'bq17', 'bq18_1', 'bq18_2', 'bq18_3', 'bq18_4', 'bq18_5', 'bq18_6', 'bq18_7', 'bq18_8', 'bq18_9', 'bq18_10', 'bq19', 'bq20', 'bq20_1', 'bq21_1', 'bq21_2', 'bq21_3', 'bq22', 'bq23', 'bq24', 'bq25', 'bq26', 'bq27', 'bq27_1', 'bq28', 'bq28_1', 'bq28_2', 'bq29', 'bq30', 'bq31_1', 'bq31_2', 'bq31_3'], '2020': ['bq18_10']}

In [14]:
# test set에 대하여 공백이 아닌 null 값이 존재함 : 확인해보자

null_test_dict = {}
for year, df in zip(years, know_test):
    null_sum = df.isnull().sum()
    null_test_dict[year] = list(null_sum[null_sum!=0].index)    
    print(year,'의 null 합계 :',null_sum.sum())
    print()

# null 값이 나타난 문항들    
print(null_test_dict)

2017 의 null 합계 : 0

2018 의 null 합계 : 35

2019 의 null 합계 : 15

2020 의 null 합계 : 3

{'2017': [], '2018': ['bq41_1', 'bq41_2', 'bq41_3'], '2019': ['bq28_1', 'bq28_2', 'bq29', 'bq30', 'bq31_1', 'bq31_2', 'bq31_3'], '2020': ['bq18_10']}

In [16]:
# null이 나타난 문항 중에서 text를 요구하는 문항이 많았나?_train
for year in years:
    print(year)
    print('null 값이 나타난 문항 수 :',len(null_train_dict[year]))
    print(set(null_train_dict[year]).intersection(set(text_dict[year])))
    print()

2017
null 값이 나타난 문항 수 : 0
set()

2018
null 값이 나타난 문항 수 : 4
set()

2019
null 값이 나타난 문항 수 : 46
{'bq18_10', 'bq27_1', 'bq22', 'bq23', 'bq20_1', 'bq24'}

2020
null 값이 나타난 문항 수 : 1
{'bq18_10'}

In [17]:
# null이 나타난 문항 중에서 text를 요구하는 문항이 많았나?_test
for year in years:
    print(year)
    print('null 값이 나타난 문항 수 :',len(null_test_dict[year]))
    print(set(null_test_dict[year]).intersection(set(text_dict[year])))
    print()

2017
null 값이 나타난 문항 수 : 0
set()

2018
null 값이 나타난 문항 수 : 3
set()

2019
null 값이 나타난 문항 수 : 7
set()

2020
null 값이 나타난 문항 수 : 1
{'bq18_10'}

In [18]:
# nan 값을 0으로 대체합시다
for df in know_train:
    df.fillna('0',inplace=True)

for df in know_test:
    df.fillna('0',inplace=True)

Nan 값의 개수가 적다. 또한 연도별로 Nan 값의 패턴은 보이지 않는 듯. text라고 해서 null 값이 무조건 나타나는 것도 아닌듯 하다

다른 값으로 대체하거나 drop하여도 성능 상에서 별 문제가 되지 않을까 싶다.

In [19]:
# 공백이 주로 어떤 문항에서 많이 등장하는가? train

blank_train_dict = {}
for year, df in zip(years,know_train):
    blank_dist = pd.DataFrame(index=['blank_sum'])
    for col in df.columns:
        blank_dist[col] = df[df[col]==' '].shape[0] 
    blank_train_dict[year] = blank_dist
    
# 공백이 주로 어떤 문항에서 많이 등장하는가? test

blank_test_dict = {}
for year, df in zip(years,know_test):
    blank_dist = pd.DataFrame(index=['blank_sum'])
    for col in df.columns:
        blank_dist[col] = df[df[col]==' '].shape[0] 
    blank_test_dict[year] = blank_dist

In [20]:
blank_train_dict['2017']

,idx,aq1_1,aq1_2,aq2_1,aq2_2,aq3_1,aq3_2,aq4_1,aq4_2,aq5_1,aq5_2,aq6_1,aq6_2,aq7_1,aq7_2,aq8_1,aq8_2,aq9_1,aq9_2,aq10_1,aq10_2,aq11_1,aq11_2,aq12_1,aq12_2,aq13_1,aq13_2,aq14_1,aq14_2,aq15_1,aq15_2,aq16_1,aq16_2,aq17_1,aq17_2,aq18_1,aq18_2,aq19_1,aq19_2,aq20_1,aq20_2,aq21_1,aq21_2,aq22_1,aq22_2,aq23_1,aq23_2,aq24_1,aq24_2,aq25_1,aq25_2,aq26_1,aq26_2,aq27_1,aq27_2,aq28_1,aq28_2,aq29_1,aq29_2,aq30_1,aq30_2,aq31_1,aq31_2,aq32_1,aq32_2,aq33_1,aq33_2,aq34_1,aq34_2,aq35_1,aq35_2,aq36_1,aq36_2,aq37_1,aq37_2,aq38_1,aq38_2,aq39_1,aq39_2,aq40_1,aq40_2,aq41_1,aq41_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15_1,bq15_2,bq15_3,bq16,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq19,bq19_1,bq20,bq21,bq22,bq23,bq24_1,bq24_2,bq24_3,bq24_4,bq24_5,bq24_6,bq24_7,bq24_8,bq25,bq26,bq27,bq28,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq38,bq38_1,bq39_1,bq39_2,bq40,bq41_1,bq41_2,bq41_3,knowcode
blank_sum,0,0,585,0,861,0,843,0,3118,0,2282,0,1676,0,1537,0,1606,0,1396,0,942,0,2745,0,1064,0,1445,0,1550,0,764,0,1871,0,3232,0,4106,0,1909,0,4612,0,4408,0,4536,0,4874,0,1532,0,1900,0,1086,0,1699,0,551,0,1881,0,2545,0,1747,0,2654,0,1566,0,1103,0,2667,0,2232,0,1968,0,2164,0,2487,0,4985,0,3586,0,0,0,0,5386,8502,9229,0,4976,4977,0,0,0,0,0,0,0,0,0,1630,1343,879,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,253,364,948,0,0,0,0,271,0,0,1301,1332,8222,1316,0

In [21]:
blank_train_dict['2018']

,idx,cq1,cq2,cq3,cq4,cq5,cq6,cq7,cq8,cq9,cq10,cq11,cq12,cq13,cq14,cq15,cq16,cq17,cq18,cq19,cq20,cq21,cq22,cq23,cq24,cq25,cq26,cq27,cq28,cq29,cq30,cq31,cq32,cq33,cq34,cq35,cq36,cq37,cq38,cq39,cq40,cq41,cq42,cq43,cq44,cq45,cq46,cq47,cq48,cq49,cq50_1,cq50_2,cq50_3,cq50_4,cq50_5,cq50_6,cq50_7,cq50_8,iq1,iq2,iq3,iq4,iq5,iq6,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15,bq16,bq17,bq18,bq19,bq20,bq21,bq221,bq222,bq223,bq231,bq232,bq233,bq234,bq235,bq241,bq242,bq243,bq244,bq245,bq25,bq25_1,bq26_1,bq26_1a,bq26_2,bq26_2a,bq26_3,bq26_3a,bq26_4,bq26_4a,bq27,bq28,bq28_1,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq37_1,bq38,bq38_1,bq38_2,bq39,bq40,bq41_1,bq41_2,bq41_3,knowcode
blank_sum,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,5078,7719,8674,10,4357,4346,0,0,0,0,0,0,0,0,1,1174,1008,750,0,0,0,0,0,0,0,0,0,1,1956,7797,2,2250,0,0,31,7736,3577,7530,8939,8598,7519,3,830,3,2385,3,1777,6,2566,8,2796,0,0,20,3621,20,3418,4047,5259,0,0,1,0,485,1,1295,7777,1295,2,1269,1387,7790,0

In [22]:
blank_train_dict['2019']

,idx,sq1,sq2,sq3,sq4,sq5,sq6,sq7,sq8,sq9,sq10,sq11,sq12,sq13,sq14,sq15,sq16,kq1_1,kq1_2,kq2_1,kq2_2,kq3_1,kq3_2,kq4_1,kq4_2,kq5_1,kq5_2,kq6_1,kq6_2,kq7_1,kq7_2,kq8_1,kq8_2,kq9_1,kq9_2,kq10_1,kq10_2,kq11_1,kq11_2,kq12_1,kq12_2,kq13_1,kq13_2,kq14_1,kq14_2,kq15_1,kq15_2,kq16_1,kq16_2,kq17_1,kq17_2,kq18_1,kq18_2,kq19_1,kq19_2,kq20_1,kq20_2,kq21_1,kq21_2,kq22_1,kq22_2,kq23_1,kq23_2,kq24_1,kq24_2,kq25_1,kq25_2,kq26_1,kq26_2,kq27_1,kq27_2,kq28_1,kq28_2,kq29_1,kq29_2,kq30_1,kq30_2,kq31_1,kq31_2,kq32_1,kq32_2,kq33_1,kq33_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq22,bq23,bq24,bq25,bq26,bq27,bq27_1,bq28,bq28_1,bq28_2,bq29,bq30,bq31_1,bq31_2,bq31_3,knowcode
blank_sum,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4443,7435,8210,0,3989,4704,0,0,0,0,0,1,0,1,0,0,0,0,1,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5899,0,0,1597,0,0,4,5300,6436,7875,0,0,0,480,0,1271,7280,1265,20,1413,1500,7333,0

In [23]:
blank_train_dict['2020']

,idx,saq1_1,saq1_2,saq2_1,saq2_2,saq3_1,saq3_2,saq4_1,saq4_2,saq5_1,saq5_2,saq6_1,saq6_2,saq7_1,saq7_2,saq8_1,saq8_2,saq9_1,saq9_2,saq10_1,saq10_2,saq11_1,saq11_2,saq12_1,saq12_2,saq13_1,saq13_2,saq14_1,saq14_2,saq15_1,saq15_2,saq16_1,saq16_2,saq17_1,saq17_2,saq18_1,saq18_2,saq19_1,saq19_2,saq20_1,saq20_2,saq21_1,saq21_2,saq22_1,saq22_2,saq23_1,saq23_2,saq24_1,saq24_2,saq25_1,saq25_2,saq26_1,saq26_2,saq27_1,saq27_2,saq28_1,saq28_2,saq29_1,saq29_2,saq30_1,saq30_2,saq31_1,saq31_2,saq32_1,saq32_2,saq33_1,saq33_2,saq34_1,saq34_2,saq35_1,saq35_2,saq36_1,saq36_2,saq37_1,saq37_2,saq38_1,saq38_2,saq39_1,saq39_2,saq40_1,saq40_2,saq41_1,saq41_2,saq42_1,saq42_2,saq43_1,saq43_2,saq44_1,saq44_2,vq1,vq2,vq3,vq4,vq5,vq6,vq7,vq8,vq9,vq10,vq11,vq12,vq13,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq14_6,bq14_7,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq16_6,bq16_7,bq16_8,bq16_9,bq16_10,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq21_4,bq22_1,bq22_2,bq22_3,bq22_4,bq22_5,bq22_6,bq23_1,bq23_2,bq23_3,bq24,bq25,bq26,bq26_1,bq27_1,bq27_2,bq28,bq29,bq30_1,bq30_2,bq30_3,knowcode
blank_sum,0,0,676,0,457,0,1606,0,836,0,1705,0,1312,0,2175,0,845,0,531,0,1546,0,1821,0,1297,0,515,0,1490,0,1378,0,1118,0,2006,0,2356,0,1591,0,1159,0,676,0,1042,0,878,0,2700,0,2252,0,2651,0,2144,0,3176,0,2106,0,2975,0,2246,0,2690,0,2042,0,2319,0,2762,0,2668,0,2702,0,2125,0,2026,0,2104,0,1999,0,2119,0,542,0,1183,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3847,6958,7878,0,5816,5816,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6692,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,134,0,0,2,0,1016,1018,7104,0

In [24]:
blank_test_dict['2017']

,idx,aq1_1,aq1_2,aq2_1,aq2_2,aq3_1,aq3_2,aq4_1,aq4_2,aq5_1,aq5_2,aq6_1,aq6_2,aq7_1,aq7_2,aq8_1,aq8_2,aq9_1,aq9_2,aq10_1,aq10_2,aq11_1,aq11_2,aq12_1,aq12_2,aq13_1,aq13_2,aq14_1,aq14_2,aq15_1,aq15_2,aq16_1,aq16_2,aq17_1,aq17_2,aq18_1,aq18_2,aq19_1,aq19_2,aq20_1,aq20_2,aq21_1,aq21_2,aq22_1,aq22_2,aq23_1,aq23_2,aq24_1,aq24_2,aq25_1,aq25_2,aq26_1,aq26_2,aq27_1,aq27_2,aq28_1,aq28_2,aq29_1,aq29_2,aq30_1,aq30_2,aq31_1,aq31_2,aq32_1,aq32_2,aq33_1,aq33_2,aq34_1,aq34_2,aq35_1,aq35_2,aq36_1,aq36_2,aq37_1,aq37_2,aq38_1,aq38_2,aq39_1,aq39_2,aq40_1,aq40_2,aq41_1,aq41_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15_1,bq15_2,bq15_3,bq16,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq19,bq19_1,bq20,bq21,bq22,bq23,bq24_1,bq24_2,bq24_3,bq24_4,bq24_5,bq24_6,bq24_7,bq24_8,bq25,bq26,bq27,bq28,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq38,bq38_1,bq39_1,bq39_2,bq40,bq41_1,bq41_2,bq41_3
blank_sum,0,0,598,0,862,0,785,0,3099,0,2170,0,1612,0,1470,0,1546,0,1352,0,908,0,2742,0,1076,0,1436,0,1535,0,771,0,1842,0,3300,0,4158,0,1885,0,4606,0,4404,0,4526,0,4835,0,1528,0,1836,0,1039,0,1707,0,538,0,1837,0,2441,0,1728,0,2649,0,1528,0,1094,0,2635,0,2266,0,1952,0,2072,0,2424,0,4982,0,3598,0,0,0,0,5433,8477,9207,0,4774,4775,0,0,0,0,0,0,0,0,0,1609,1332,884,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5,284,388,959,0,0,0,0,278,0,0,1333,1371,8191,1342

In [25]:
blank_test_dict['2018']

,idx,cq1,cq2,cq3,cq4,cq5,cq6,cq7,cq8,cq9,cq10,cq11,cq12,cq13,cq14,cq15,cq16,cq17,cq18,cq19,cq20,cq21,cq22,cq23,cq24,cq25,cq26,cq27,cq28,cq29,cq30,cq31,cq32,cq33,cq34,cq35,cq36,cq37,cq38,cq39,cq40,cq41,cq42,cq43,cq44,cq45,cq46,cq47,cq48,cq49,cq50_1,cq50_2,cq50_3,cq50_4,cq50_5,cq50_6,cq50_7,cq50_8,iq1,iq2,iq3,iq4,iq5,iq6,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13,bq14,bq15,bq16,bq17,bq18,bq19,bq20,bq21,bq221,bq222,bq223,bq231,bq232,bq233,bq234,bq235,bq241,bq242,bq243,bq244,bq245,bq25,bq25_1,bq26_1,bq26_1a,bq26_2,bq26_2a,bq26_3,bq26_3a,bq26_4,bq26_4a,bq27,bq28,bq28_1,bq29,bq30,bq31,bq32,bq33,bq34,bq35,bq36,bq37,bq37_1,bq38,bq38_1,bq38_2,bq39,bq40,bq41_1,bq41_2,bq41_3
blank_sum,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,5129,7780,8671,9,4248,4237,0,0,0,0,0,0,0,0,0,1134,1026,711,0,0,0,0,0,0,0,0,0,0,2005,7783,2,2241,0,0,30,7792,3524,7601,8946,8583,7514,1,850,1,2367,0,1779,4,2527,6,2688,0,0,19,3560,20,3349,3956,5185,0,0,0,3,426,1,1327,7742,1331,0,1297,1422,7761

In [26]:
blank_test_dict['2019']

,idx,sq1,sq2,sq3,sq4,sq5,sq6,sq7,sq8,sq9,sq10,sq11,sq12,sq13,sq14,sq15,sq16,kq1_1,kq1_2,kq2_1,kq2_2,kq3_1,kq3_2,kq4_1,kq4_2,kq5_1,kq5_2,kq6_1,kq6_2,kq7_1,kq7_2,kq8_1,kq8_2,kq9_1,kq9_2,kq10_1,kq10_2,kq11_1,kq11_2,kq12_1,kq12_2,kq13_1,kq13_2,kq14_1,kq14_2,kq15_1,kq15_2,kq16_1,kq16_2,kq17_1,kq17_2,kq18_1,kq18_2,kq19_1,kq19_2,kq20_1,kq20_2,kq21_1,kq21_2,kq22_1,kq22_2,kq23_1,kq23_2,kq24_1,kq24_2,kq25_1,kq25_2,kq26_1,kq26_2,kq27_1,kq27_2,kq28_1,kq28_2,kq29_1,kq29_2,kq30_1,kq30_2,kq31_1,kq31_2,kq32_1,kq32_2,kq33_1,kq33_2,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq22,bq23,bq24,bq25,bq26,bq27,bq27_1,bq28,bq28_1,bq28_2,bq29,bq30,bq31_1,bq31_2,bq31_3
blank_sum,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4441,7451,8231,0,4066,4703,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5853,0,0,1615,0,0,2,5318,6380,7864,0,1,0,480,3,1227,7325,1226,23,1382,1476,7381

In [27]:
blank_test_dict['2020']

,idx,saq1_1,saq1_2,saq2_1,saq2_2,saq3_1,saq3_2,saq4_1,saq4_2,saq5_1,saq5_2,saq6_1,saq6_2,saq7_1,saq7_2,saq8_1,saq8_2,saq9_1,saq9_2,saq10_1,saq10_2,saq11_1,saq11_2,saq12_1,saq12_2,saq13_1,saq13_2,saq14_1,saq14_2,saq15_1,saq15_2,saq16_1,saq16_2,saq17_1,saq17_2,saq18_1,saq18_2,saq19_1,saq19_2,saq20_1,saq20_2,saq21_1,saq21_2,saq22_1,saq22_2,saq23_1,saq23_2,saq24_1,saq24_2,saq25_1,saq25_2,saq26_1,saq26_2,saq27_1,saq27_2,saq28_1,saq28_2,saq29_1,saq29_2,saq30_1,saq30_2,saq31_1,saq31_2,saq32_1,saq32_2,saq33_1,saq33_2,saq34_1,saq34_2,saq35_1,saq35_2,saq36_1,saq36_2,saq37_1,saq37_2,saq38_1,saq38_2,saq39_1,saq39_2,saq40_1,saq40_2,saq41_1,saq41_2,saq42_1,saq42_2,saq43_1,saq43_2,saq44_1,saq44_2,vq1,vq2,vq3,vq4,vq5,vq6,vq7,vq8,vq9,vq10,vq11,vq12,vq13,bq1,bq2,bq3,bq4,bq4_1a,bq4_1b,bq4_1c,bq5,bq5_1,bq5_2,bq6,bq7,bq8_1,bq8_2,bq8_3,bq9,bq10,bq11,bq12_1,bq12_2,bq12_3,bq12_4,bq12_5,bq13_1,bq13_2,bq13_3,bq14_1,bq14_2,bq14_3,bq14_4,bq14_5,bq14_6,bq14_7,bq15,bq16_1,bq16_2,bq16_3,bq16_4,bq16_5,bq16_6,bq16_7,bq16_8,bq16_9,bq16_10,bq17,bq18_1,bq18_2,bq18_3,bq18_4,bq18_5,bq18_6,bq18_7,bq18_8,bq18_9,bq18_10,bq19,bq20,bq20_1,bq21_1,bq21_2,bq21_3,bq21_4,bq22_1,bq22_2,bq22_3,bq22_4,bq22_5,bq22_6,bq23_1,bq23_2,bq23_3,bq24,bq25,bq26,bq26_1,bq27_1,bq27_2,bq28,bq29,bq30_1,bq30_2,bq30_3
blank_sum,0,0,683,0,456,0,1618,0,890,0,1689,0,1342,0,2148,0,873,0,595,0,1554,0,1786,0,1353,0,537,0,1506,0,1384,0,1165,0,2034,0,2323,0,1671,0,1179,0,689,0,1079,0,911,0,2727,0,2245,0,2646,0,2154,0,3189,0,2187,0,2949,0,2281,0,2727,0,2048,0,2299,0,2758,0,2667,0,2709,0,2042,0,2078,0,2088,0,2029,0,2226,0,524,0,1260,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3881,7059,7888,0,5822,5822,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6739,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,156,0,0,6,0,1014,1014,7108

설문지와 공백의 개수를 비교해보면서 보았는데, 공백이 드러난 부분은 문항에서 필요에 따라 건너뛰라고 지시한 부분이었다.
혹은 text로 작성하는 문항이었다.
blank_sum이 0으로 나타나는 문항들이 꽤 많은데, 이 부분은 참가자가 반드시 마킹을 해야하는 부분이다.
즉, 참여자들이 설문지를 굉장히 모범적으로 작성했으며 설문지 수합 데이터에는 큰 이상이 없다고 말할 수 있겠다.

**Baseline에서 나타났던 공백을 0으로 채우는 부분은 좋은 아이디어인듯! 설문지에 0이라는 응답보기는 없음!**

In [28]:
# train set에 대하여 공백은 모두 str 0으로 전환
for df in know_train:
    for col in df.columns:
        df[col].replace(' ', '0', inplace=True)

In [29]:
# test set에 대하여 공백은 모두 str 0으로 전환
for df in know_test:
    for col in df.columns:
        df[col].replace(' ', '0', inplace=True)

# 데이터 타입에 대하여

In [31]:
# int type으로 바꾸는 것을 시도해보고 안된다면 str로 취급하여 정리해봅시다 
print('train')
for year, df in zip(years, know_train):
    print(year)
    
    for col in df.columns:
        try:
            df[col] = df[col].map(int) 
        except:
            df[col] = df[col].map(str)
print()
print('test')
for year, df in zip(years, know_test):
    print(year)
    
    for col in df.columns:
        try:
            df[col] = df[col].map(int) 
        except:
            df[col] = df[col].map(str)

train
2017
2018
2019
2020

test
2017
2018
2019
2020

In [33]:
def check_datatype_integrity(years, know_data, verbose=True):
    
    trouble_candidate_dict = {}
    
    # 데이터 타입 변환이 잘 이루어졌는지 체크하고 문제가 있는 문항을 딕셔너리에 담습니다
    for year,df in zip(years,know_data):
        compare_a = set(df.dtypes[df.dtypes=='object'].index)
        compare_b = set(text_dict[year])
        if verbose == True:
            print(year)
        if (compare_a - compare_b) == set():
            if verbose == True:
                print('데이터 타입 변환이 잘 이루어 졌습니다')
            trouble_candidate_dict[year] = (compare_a - compare_b)
        else:
            if verbose == True:
                print('문제가 생겼습니다 아래 문항들의 데이터 타입을 확인해보세요')
                print(compare_a - compare_b)
            trouble_candidate_dict[year] = (compare_a - compare_b)
    if verbose == True:
        print('-'*20)    
    
    # 문제가 있는 문항을 출력해서 하나씩 살펴봅시다
    trouble_dict = {}
    
    for year in years:
        trouble_dict[year] = []
        
    for year,df in zip(years,know_data):
        if verbose == True:
            print(year,'년 오류문항 Overview')
            for col in trouble_candidate_dict[year]:
                print(col,':',df[col].unique())
            print()
        for col in trouble_candidate_dict[year]:
            try:
                df[col] = df[col].map(float) # float으로 바꿀 수 있다면 바꿔주고
            except:
                trouble_dict[year].append(col) # 오류가 있다면 딕셔너리에 담아줍시다
    
    return trouble_dict

In [51]:
trouble_train_dict = check_datatype_integrity(years, know_train, verbose=False)

In [42]:
trouble_test_dict = check_datatype_integrity(years, know_test, verbose=False)

In [49]:
# 숫자로 답변해야하는데 설문자가 주관식으로 답변해 str로 처리된 문제 문항들
trouble_train_dict

{'2017': [],
 '2018': ['bq36', 'bq34', 'bq37', 'bq40', 'bq35', 'bq5_1', 'bq28', 'bq4'],
 '2019': ['bq27',
  'bq21_3',
  'bq8_3',
  'bq20',
  'bq11',
  'bq7',
  'bq9',
  'bq25',
  'bq12_4',
  'bq10',
  'bq6'],
 '2020': []}

In [37]:
# 숫자로 답변해야하는데 설문자가 주관식으로 답변해 str로 처리된 문제 문항들
trouble_test_dict

{'2017': [],
 '2018': ['bq37', 'bq35', 'bq5_1', 'bq28', 'bq4'],
 '2019': ['bq27', 'bq21_3', 'bq19', 'bq20'],
 '2020': []}

In [192]:
know_train, know_test = data_reproduction()

## 2017년 : 설문자의 실수로 잘못기입된 데이터 바꾸기
-> 아무도 실수 안해서 바꿀게 없음

In [193]:
df = know_train[0]
df.to_csv('KNOW_2017_train.csv',index=False)
df = know_test[0]
df.to_csv('KNOW_2017_test.csv',index=False)

## 2018년 : 설문자의 실수로 잘못기입된 데이터 바꾸기
-> train : ['bq36', 'bq34', 'bq37', 'bq40', 'bq35', 'bq5_1', 'bq28', 'bq4']  
-> test : ['bq37', 'bq35', 'bq5_1', 'bq28', 'bq4']

#### train
- bq36 고쳐보기

In [194]:
df = know_train[1]

In [195]:
# 디자이너가 문제니까 디자이너만 바꿔주자
print(df['bq36'].unique())
df.loc[df[df['bq36']=='디자이너'].index,'bq36'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq36'] = df['bq36'].map(float) # 데이터 타입도 바꿔주기

['27.0' '28.0' '59.0' '38.0' '26.0' '33.0' '37.0' '32.0' '43.0' '52.0'
 '35.0' '72.0' '34.0' '50.0' '29.0' '49.0' '60.0' '45.0' '39.0' '57.0'
 '56.0' '58.0' '44.0' '23.0' '47.0' '53.0' '51.0' '41.0' '48.0' '54.0'
 '31.0' '30.0' '36.0' '83.0' '78.0' '70.0' '24.0' '40.0' '46.0' '42.0'
 '25.0' '20.0' '68.0' '63.0' '67.0' '21.0' '61.0' '66.0' '71.0' '55.0'
 '64.0' '73.0' '62.0' '65.0' '4.0' '22.0' '74.0' '80.0' '19.0' '69.0'
 '2.0' '77.0' '76.0' '79.0' '75.0' '85.0' '3.0' '5.0' '81.0' '31' '38'
 '56' '43' '45' '57' '26' '42' '52' '67' '41' '0' '48' '50' '40' '47' '58'
 '36' '55' '28' '33' '34' '32' '35' '46' '25' '49' '37' '44' '61' '27'
 '53' '29' '59' '30' '63' '39' '64' '23' '21' '24' '66' '54' '60' '51'
 '75' '62' '70' '68' '72' '디자이너' '80' '65' '69' '4' '82' '17' '22' '3']

* bq34 고쳐보기

In [196]:
# 자동차과, 포토샵이 문제니까 바꿔주자
print(df['bq34'].unique())
df.loc[df[df['bq34']=='자동차과'].index,'bq34'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df.loc[df[df['bq34']==' 포토샵'].index,'bq34'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq34'] = df['bq34'].map(float) # 데이터 타입도 바꿔주기

['3.0' '4.0' '2.0' '1.0' '5.0' '3' '4' '2' '자동차과' '5' '1' ' 포토샵']

- bq37 고쳐보기

In [197]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq37'].unique())
remove_set = {'1','2','3','4','5','6'}
new_words_list = [i for i in df['bq37'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq37']==word].index,'bq37'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq37'] = df['bq37'].map(float) # 데이터 타입도 바꿔주기

['3' '2' '4' '5' '6' '1' '전자전기학' '정보처리' '금속' '이' '전기공학' '전자공학' '시각디자인'
 '공고졸업' '기계' '이과' '전기전자' '전자전기 공학' '금속기계' '항해학과' '금속가공' '기계과' '전기'
 '전자전기공학' '기계공학' '세무회계' '멀티미디어' '자동차' '디자이너' '기계학']

* bq40 고쳐보기

In [198]:
# 지식재산학이 문제니까 지식재산학만 바꿔주자
print(df['bq40'].unique())
df.loc[df[df['bq40']=='지식재산학'].index,'bq40'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq40'] = df['bq40'].map(float) # 데이터 타입도 바꿔주기

['42' '40' '30.0' '38' '60' '54' '56' '46' '50' '35' '40.0' '52' '44' '45'
 '70' '48' '30' '49' '48.0' '44.0' '62' '50.0' '45.0' '90.0' '60.0' '55.0'
 '52.0' '32' '56.0' '72' '55' '75.0' '35.0' '66' '41' '54.0' '25' '43'
 '12' '47.0' '36.0' '72.0' '20' '90' '20.0' '75' '53' '58' '3000.0' '32.0'
 '53.0' '25.0' '49.0' '47' '65' '11' '34' '66.0' '21' '18' '3' '58.0'
 '46.0' '33' '63.0' '9' '74' '16' '84.0' '61.0' '38.0' '28' '42.0' '59'
 '36' '51' '65.0' '10' '70.0' '28.0' '10.0' '13' '43.0' '2800.0' '14' '8'
 '5000.0' '98' '62.0' '6' '64' '5200.0' '24' '51.0' '80.0' '37' '15' '80'
 '71.0' '31' '0' '57.0' '15.0' '3500.0' '27' '33.0' '4900.0' '13.0' '68'
 '68.0' '69' '8000.0' '74.0' '5500.0' '21.0' '12.0' '69.0' '24.0' '18.0'
 '4000.0' '34.0' '64.0' '3800.0' '78.0' '37.0' '41.0' '6000.0' '5.0' '6.0'
 '8.0' '3100.0' '7.0' '23.0' '27.0' '7000.0' '2900.0' '11.0' '26.0' '17.0'
 '14.0' '59.0' '4300.0' '73.0' '4500.0' '4800.0' '지식재산학' '17' '63'
 '5600.0' '3200.0']

* bq35 고쳐보기

In [199]:
# 지식재산학이 문제니까 지식재산학만 바꿔주자
print(df['bq35'].unique())
df.loc[df[df['bq35']==' 라이트룸 등의 컴퓨터 프로그램"'].index,'bq35'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq35'] = df['bq35'].map(float) # 데이터 타입도 바꿔주기

['1.0' '2.0' '27.0' '40.0' '31.0' '53.0' '39.0' '26.0' '32.0' '52.0'
 '50.0' '42.0' '35.0' '46.0' '37.0' '25.0' '44.0' '47.0' '56.0' '1' '2'
 ' 라이트룸 등의 컴퓨터 프로그램"' '42' '33' '45' '38' '30']

* bq5_1 고쳐보기

In [200]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq5_1'].unique())
remove_set = {'1','2','3','4','5','6','0'}
new_words_list = [i for i in df['bq5_1'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq5_1']==word].index,'bq5_1'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq5_1'] = df['bq5_1'].map(float) # 데이터 타입도 바꿔주기

['3' '5' '0' '4' '2' '6' '1' '전기설비유지보수' '직무관련 실습' '전기철도개요및 시공실습 등'
 '직무교육, 현장안전교육, 도구사용법' '지게차 자격증' '지게차자격증' '기본지식,실무 훈련' '전기실무' '설비관련 지식'
 '장비관련유지보수 관리법' '전기기술실무' 'PCB기판검등,설계,수리,PLC,전기기기회로' '프로그램 툴사용.제품구조 이해'
 'OJT' '실무교육' '기계조작 직무 교육' '안전업무' '직무향상 교육' '기계장치이해, 배선도면 이해'
 '전기시공실습,안전교육']

* bq28 고쳐보기

In [201]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq28'].unique())
remove_set = {'1','2','3','4','5'}
new_words_list = [i for i in df['bq28'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq28']==word].index,'bq28'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq28'] = df['bq28'].map(float) # 데이터 타입도 바꿔주기

['4' '2' '3' '1' '5' '자동화' '기계의 자동화로 감소' '철강제조업의 불황으로 큰변화는 없을것 같아서'
 '1차산업이 늘어나지는 않을것이다' '4차 산업혁명및 자동화 등' '전산화,인공지능도 있지만 수작업필요'
 '인쇄물 위주의 작업이기때문에 미디어가 계속 성장하면서 인쇄작업량이 줄어들것으로 생각됩니다.'
 '3D업종이라 할려는 사람들이 줄어들고 있어서' '아파트 및 교량 건설이 많을것이므로' '아파트 및 교량 건설이 많을 것이므로'
 '자동화로 인하여 일자리감소' '자동,외주화' '일이 힘이 들어서 할려는 사람이 없다' '많은 아파트 등에서 철근이 필요하므로'
 '수출이 갈수록 힘들어질것 같아서' '기계의 자동화로 인해서' '외주화,자동화' '정년이 어느정도 정해져 있어서'
 '일이 힘이 들어서' '기계화,자동화,외주화' '차량도입이 증가하고 있기때문' '기술의 발전으로 적은 인원으로 일처리가 가능'
 '자동화가 되어가기 때문에' '자동화가 가속화 될것' '수요가 꾸준' '통일이 된다면 비젼이 매우 크기 때문'
 '자동화설비의 보급 확대로' '배우는 인력이 없어 일거리가 늘어남' '제조경기가 전반적으로 어려워서' '업무가 갈수록 간소화 췌'
 '산업발달로인한 인력필요']

* bq4 고쳐보기

In [202]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq4'].unique())
remove_set = {'1','2','0'}
new_words_list = [i for i in df['bq4'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq4']==word].index,'bq4'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq4'] = df['bq4'].map(float) # 데이터 타입도 바꿔주기

['1' '2' '전기기사' '0' '금속재료시험 기능사' '전기철도기사' '제강기능사' '열처리기능사']

In [203]:
df.to_csv('KNOW_2018_train.csv',index=False)

#### test
* bq37

In [204]:
df = know_test[1]

In [205]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq37'].unique())
remove_set = {'1','2','3','4','5','6','0'}
new_words_list = [i for i in df['bq37'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq37']==word].index,'bq37'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq37'] = df['bq37'].map(float) # 데이터 타입도 바꿔주기

['1' '4' '3' '2' '5' '6' '공고졸업' '금속' '전기' '이과' '전기공학' '전산응용가공' '신소재디자인'
 '인문' '기계' '기계학' '항공우주 시스템공학' '전기전자' '0' '사회복지학' '정보통신학' '이' '간호학과'
 '신소재공학' '전기전자학' '시각디자인학' '전자공학' '기계과']

* bq35

In [206]:
# 문예창작이 문제니까 문예창작만 바꿔주자
print(df['bq35'].unique())
df.loc[df[df['bq35']=='문예창작'].index,'bq35'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq35'] = df['bq35'].map(float) # 데이터 타입도 바꿔주기

['2' '1' '48' '53' '39' '50' '38' '35' '46' '29' '52' '문예창작' '1.0' '2.0'
 '40.0' '30.0' '49.0' '69.0' '31.0' '38.0' '39.0' '28.0' '54.0' '41.0'
 '26.0' '50.0' '44.0' '51.0']

* bq28

In [207]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq28'].unique())
remove_set = {'1','2','3','4','5'}
new_words_list = [i for i in df['bq28'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq28']==word].index,'bq28'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq28'] = df['bq28'].map(float) # 데이터 타입도 바꿔주기

['1' '2' '3' '4' '5' '전반적인 내수경기가 어려워지고 있어서' '3D업종이라서' '외주화,자동화' '외주화'
 '국가의 기간 산업이므로' '직접고용이 늘어서' '경기불황이 계속될것이라서' '사업증설 기피.단가 인상 동결'
 '건축 등에 철근재가 필요함' 'KTX의 이용증가로' '기계의 자동화로 인해서' '자동화 될 가능성이 높다'
 '차량도입 및 유지보수의 증가 필요' '전산화,인공지능, 4차혁명, 빅데이터 등 발전하여 변화됨' '자동화로 인한 일자리 감소'
 '근무형태 변화' '사업체 감소로' '힘든업종이라서' '업무 자동화에 대한 한계가 있음, 주로 직접 사람이 작업을 해야함'
 '전기는 변하지 않음' '사람이 해야 할 일이 어느 정도는 있을 것 같아서' '일을 할려는 사람이 없다'
 '꾸준함/변하지 않고 일정함' '자동화되어도 수작업이 필요' '근무환경이 열악해서 젊은이들이 배울려고 하질 않음'
 '어느정도는 사람이 해야하는 일이므로' '어느정도는 사람이 해야 하는 일이 있으므로']

* bq5_1

In [208]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq5_1'].unique())
remove_set = {'1','2','3','4','5','0'}
new_words_list = [i for i in df['bq5_1'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq5_1']==word].index,'bq5_1'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq5_1'] = df['bq5_1'].map(float) # 데이터 타입도 바꿔주기

['0' '3' '4' '2' '1' '6' '5' '현장기기조작 교육' '전기 실무' '전기기술' '직무 관련 교육'
 '전기도면의이해, 기계장치의 이해' '현장에서 배우는 기술들' '전기실무기술' '품질혁신. 생산 계획수립'
 '고속차량 유지보수 교육(전자장비)' '직무교육' '설비 유지보수 훈련' '안전교육'
 '직무역량 훈련, 기타 안전관력 전반적인 지속적 훈련필요' '전기실무' '전기직업교육' '전기기술실무' '설비 조작방법'
 '전기설비 교육' '전문교육' '직무관련 안전교육']

In [209]:
df.to_csv('KNOW_2018_test.csv',index=False)

## 2019년 : 설문자의 실수로 잘못기입된 데이터 바꾸기
-> train : ['bq25','bq10','bq8_3','bq12_4','bq20','bq9','bq11','bq27','bq21_3','bq6','bq7']   
-> test : ['bq19', 'bq21_3', 'bq27', 'bq20']

#### train
* bq25

In [210]:
df = know_train[2]

In [211]:
# 일러스트레이터가 문제니까 일러스트레이터만 바꿔주자
print(df['bq25'].unique())
df.loc[df[df['bq25']==' 일러스트레이터"'].index,'bq25'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq25'] = df['bq25'].map(float) # 데이터 타입도 바꿔주기

['1' '2' '43' '26' ' 일러스트레이터"' '0' '34' '28' '44']

* bq10

In [212]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq10'].unique())
remove_set = {'1','2','3','4','5'}
new_words_list = [i for i in df['bq10'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq10']==word].index,'bq10'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq10'] = df['bq10'].map(float) # 데이터 타입도 바꿔주기

['4' '2' '3' '1' '5'
 '잘 떠오르지는 않으나 회사 생활을 오래 해왔기 때문에 대부분의 사무 업무는 가능할 것으로 보임'
 '가능 한지는 잘 모르겠지만,_작업하는 방향성이 비슷한 것을 생각 한다면, 게임쪽 원화가나 일러스트레이터는 가능 할 것 같습니다.']

* bq8_3

In [213]:
# 정보·기록학이 문제니까 정보·기록학만 바꿔주자
print(df['bq8_3'].unique())
df.loc[df[df['bq8_3']=='정보·기록학'].index,'bq8_3'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq8_3'] = df['bq8_3'].map(float) # 데이터 타입도 바꿔주기

['3' '4' '5' '2' '1' '정보·기록학']

* bq12_4

In [214]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq12_4'].unique())
remove_set = {'1','2','3','4','5','9'}
new_words_list = [i for i in df['bq12_4'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq12_4']==word].index,'bq12_4'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq12_4'] = df['bq12_4'].map(float) # 데이터 타입도 바꿔주기

['4' '9' '3' '5' '2' '1' '사회학과' '2400' '시각디자인']

* bq20

In [215]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq20'].unique())
remove_set = {'1','2','3','4','5','0'}
new_words_list = [i for i in df['bq20'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq20']==word].index,'bq20'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq20'] = df['bq20'].map(float) # 데이터 타입도 바꿔주기

['4' '3' '2' '1' '5'
 '어떠한 분야든 자동화가 도입이 되면, 인력 감축을 불가피하며, 대신 자동화 설비 유지관리에 추가 고용이 될 것으로 예측됨.'
 '기계 또한 프로그램 언어로 돌아가는 거니까.' '0' 'AI 자동화'
 '인공지능, 빅데이터 분석 능력의 질적 향상 등으로 시장 조사가 기존에 데이터를 구하는 방법/분석하는 방법에 대한 요구가 줄어든다']

* bq9

In [216]:
# 디자이너가 문제니까 디자이너만 바꿔주자
print(df['bq9'].unique())
df.loc[df[df['bq9']=='디자이너'].index,'bq9'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq9'] = df['bq9'].map(float) # 데이터 타입도 바꿔주기

['4' '2' '3' '1' '5' '0' '디자이너']

* bq11

In [217]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq11'].unique())
remove_set = {'1','2','3','4','5','0'}
new_words_list = [i for i in df['bq11'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq11']==word].index,'bq11'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq11'] = df['bq11'].map(float) # 데이터 타입도 바꿔주기

['4' '3' '2' '1' '5' '모바일 혹은 GPS 기술 등을 접목한 서베이 기술 관련 프로그래머/기술자??' '0'
 '잘 모르겠습니다.']

* bq27

In [218]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq27'].unique())
remove_set = {'1','2','3','4','5','0'}
new_words_list = [i for i in df['bq27'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq27']==word].index,'bq27'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq27'] = df['bq27'].map(float) # 데이터 타입도 바꿔주기

['4' '3' '2' '1' '5' '6' '지능로봇학' '모바일인터넷' '0' '영상영화디자인과' '방사선과' '컴퓨터공학'
 '신문방송']

* bq21_3

In [219]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq21_3'].unique())
remove_set = {'1','2','3','4','5','0'}
new_words_list = [i for i in df['bq21_3'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq21_3']==word].index,'bq21_3'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq21_3'] = df['bq21_3'].map(float) # 데이터 타입도 바꿔주기

['3' '4' '2' '1' '5' '로봇 엔지니어' '0' 'PET`CT 검사, 핵의학 검사']

* bq6

In [220]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq6'].unique())
remove_set = {'1','2','3','4','5','6','7','0'}
new_words_list = [i for i in df['bq6'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq6']==word].index,'bq6'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq6'] = df['bq6'].map(float) # 데이터 타입도 바꿔주기

['7' '1' '2' '4' '6' '3' '5' ' 기존 사람들이 진행하던 분석 업무들 중 일부도 대체 가능해 보임_다만'
 ' 데이터마이너"' ' 수요는 축소. 혹은 드로잉의 경우는 회사가 정규직 고용보다는 외주인력으로 돌리는 추세로 알고 있기에']

* bq7

In [221]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq7'].unique())
remove_set = {'1','2','3','4','5','6','7'}
new_words_list = [i for i in df['bq7'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq7']==word].index,'bq7'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq7'] = df['bq7'].map(float) # 데이터 타입도 바꿔주기

['4' '2' '5' '1' '7' '6' '3'
 ' 경험을 기준으로 하는 분석이나 새로운 아이디어 부분에서는 여전히 사람이 진행해야 할 것 같음"'
 ' 일자리는 아마도 게속 감소하는 방향 일 것 같습니다.__그 외 에도 인력비가 비싸다고("']

In [222]:
df.to_csv('KNOW_2019_train.csv',index=False)

#### test
* bq19

In [223]:
df = know_test[2]

In [224]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq19'].unique())
remove_set = {'1','2','3','4','5'}
new_words_list = [i for i in df['bq19'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq19']==word].index,'bq19'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq19'] = df['bq19'].map(float) # 데이터 타입도 바꿔주기

['1' '2' '4' '3' '5' ' 독립 애니메이션 감독' ' 역할만 바뀌었지 영상의 영역을 벗어나기는 힘들 것으로 보인다."']

* bq21_3

In [225]:
# 사회학/광고홍보학이 문제니까 사회학/광고홍보학만 바꿔주자
print(df['bq21_3'].unique())
df.loc[df[df['bq21_3']=='사회학/광고홍보학'].index,'bq21_3'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq21_3'] = df['bq21_3'].map(float) # 데이터 타입도 바꿔주기

['2' '3' '1' '4' '5' '0' '사회학/광고홍보학']

* bq27

In [226]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq27'].unique())
remove_set = {'1','2','3','4','5','6'}
new_words_list = [i for i in df['bq27'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq27']==word].index,'bq27'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq27'] = df['bq27'].map(float) # 데이터 타입도 바꿔주기

['4' '3' '2' '6' '5' '1' '건축' '60' '지질학과' '2900']

* bq20

In [227]:
# 주관식으로 답한 사람들이 너무 많다 전부 0으로 바꿔주자
print(df['bq20'].unique())
remove_set = {'1','2','3','4','5'}
new_words_list = [i for i in df['bq20'].unique() if i not in remove_set]

for word in new_words_list:
    df.loc[df[df['bq20']==word].index,'bq20'] = 0 # 오류인 것은 모두 0으로 바꿔주기
df['bq20'] = df['bq20'].map(float) # 데이터 타입도 바꿔주기

['4' '3' '5' '2' '1' ' 웹툰작가 등 콘텐츠를 스스로 창작해본 모든 직군"'
 '새로운 장비나 소프트웨어가 발달함에도 불구하고 각종 환경적 변화(농업환경변화, 기후변화 등)에 따른 정책적 대안을 마련하고 그에 따른 기술력 적용에 대한 판단을 요하는 직업이므로 변화가 없을 것으로 판단함.'
 '컬러리스트']

In [228]:
df.to_csv('KNOW_2019_test.csv',index=False)

## 2020년 : 설문자의 실수로 잘못기입된 데이터 바꾸기
-> 아무도 실수 안해서 바꿀게 없음

In [229]:
df = know_train[3]
df.to_csv('KNOW_2020_train.csv',index=False)
df = know_test[3]
df.to_csv('KNOW_2020_test.csv',index=False)