# Train데이터 불러오기

각 년도별 DataFrame을 리스트에 append합니다.

리스트 인덱스별로

0: 2017년도 데이터   

1: 2018년도 데이터 

2: 2019년도 데이터 

3: 202년도 데이터 

입니다

In [1]:
import pandas as pd
import numpy as np
from glob import glob
from tqdm import tqdm
import warnings

import matplotlib.pyplot as plt
import seaborn as sns

RANDOM_STATE = 42
np.seed = 42
DATA_PATH = "../data_keywords/v1/"

warnings.filterwarnings(action='ignore')
PATH_2017 = DATA_PATH + "train/keywords_2017.csv"
PATH_2018 = DATA_PATH + "train/keywords_2018.csv"
PATH_2019 = DATA_PATH + "train/keywords_2019.csv"
PATH_2020 = DATA_PATH + "train/keywords_2020.csv"

paths = [PATH_2017, PATH_2018, PATH_2019, PATH_2020]

know_train = [pd.read_csv(path) for path in paths]

In [2]:
# read index
i_PATH_2017 = "../data_0115/" + "train/KNOW_2017.csv"
i_PATH_2018 = "../data_0115/" + "train/KNOW_2018.csv"
i_PATH_2019 = "../data_0115/" + "train/KNOW_2019.csv"
i_PATH_2020 = "../data_0115/" + "train/KNOW_2020.csv"

i_paths = [i_PATH_2017, i_PATH_2018, i_PATH_2019, i_PATH_2020]
know_train_idx = [pd.read_csv(path) for path in i_paths]

In [3]:
for i in range(4):
    know_train[i].index = know_train_idx[i]['idx']
    know_train_idx[i].index = know_train_idx[i]['idx']
    know_train[i]['knowcode'] = know_train_idx[i]['knowcode']

know_train[3] # 2019년도 샘플

,개성,코딩,통관,급증,행정,안과,건설환경기사,보상,토목시공기술사,무역영어,...,공장,섬유기술사,조경기술사,어려움,공조냉동,치과의사,길경로,부서,신소재,knowcode
idx,,,,,,,,,,,,,,,,,,,,,
27127,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,304003
27128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,221401
27129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,815001
27130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,304003
27131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,140201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,121105
35245,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26102
35246,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31301
35247,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,154105
35248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14201

# 전처리 

`data_keywords`는 이미 전처리된 데이터  
매우 sparse 한 테이블

In [4]:
years = ['2017', '2018', '2019', '2020']
for i in range(4):
    print(f"{2017+i}: {know_train[i].shape}")

2017: (9486, 1953)
2018: (9072, 2438)
2019: (8555, 1854)
2020: (8122, 1792)

# X, y 구분 및 모델 학습

이번 대회에서 맞춰야 할 값은 knowcode입니다.

ID와 knowcode를 제외한 나머지 feature를 X, knowcode를 정답 y로 두어 모델을 학습하였습니다.

베이스라인에서는 의사결정나무와 랜덤포레스트를 선정하였습니다

df.drop(['idx','knowcode'], axis=1)

In [5]:
train_data = {}
for year, df in zip(years, know_train):
    train_data[year] = {'X': df.drop('knowcode', axis=1),
                        'y': df['knowcode']}

In [6]:
train_data['2019']

{'X':         코딩   통관   행정   안과  작사가  토목시공기술사  분자생물학   기간   축산  조종사  ...  동영상  에디터  \
 idx                                                            ...
 18569  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 18570  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 18571  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 18572  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 18573  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 ...    ...  ...  ...  ...  ...      ...    ...  ...  ...  ...  ...  ...  ...
 27122  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 27123  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 27124  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 27125  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0
 27126  0.0  0.0  0.0  0.0  0.0      0.0    0.0  0.0  0.0  0.0  ...  0.0  0.0

        대형면허증   통계  조경기술사  공조냉동  CG제작   부서   납부   물량
 idx
 18569    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 18570    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 18571    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 18572    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 18573    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 ...      ...  ...    ...   ...   ...  ...  ...  ...
 27122    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 27123    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 27124    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 27125    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0
 27126    0.0  0.0    0.0   0.0   0.0  0.0  0.0  0.0

 [8555 rows x 1853 columns],
 'y': idx
 18569    812301
 18570     15201
 18571    901101
 18572     29903
 18573    561401
           ...
 27122    416105
 27123    531601
 27124    615301
 27125    811901
 27126    812101
 Name: knowcode, Length: 8555, dtype: int64}

# Extra Trees Classifier

In [7]:
from sklearn.ensemble import ExtraTreesClassifier

et_models = {}

for year in tqdm(years):
    model = ExtraTreesClassifier(n_estimators=100, random_state=RANDOM_STATE, n_jobs=8)
    model.fit(train_data[year]['X'].iloc[:, :], train_data[year]['y'])
    et_models[year] = model

100%|██████████| 4/4 [00:29<00:00,  7.25s/it]

## Testset 불러오기

마찬가지로 년도별로 DataFrame으로 불러온 후 리스트에 할당합니다.

In [9]:
TEST_PATH_2017 = DATA_PATH + "test/keywords_2017_test.csv"
TEST_PATH_2018 = DATA_PATH + "test/keywords_2018_test.csv"
TEST_PATH_2019 = DATA_PATH + "test/keywords_2019_test.csv"
TEST_PATH_2020 = DATA_PATH + "test/keywords_2020_test.csv"

TEST_PATHs = [TEST_PATH_2017, TEST_PATH_2018, TEST_PATH_2019, TEST_PATH_2020]

# read index
i_TEST_PATH_2017 = "../data_0115/" + "test/KNOW_2017_test.csv"
i_TEST_PATH_2018 = "../data_0115/" + "test/KNOW_2018_test.csv"
i_TEST_PATH_2019 = "../data_0115/" + "test/KNOW_2019_test.csv"
i_TEST_PATH_2020 = "../data_0115/" + "test/KNOW_2020_test.csv"

i_test_paths = [i_TEST_PATH_2017, i_TEST_PATH_2018, i_TEST_PATH_2019, i_TEST_PATH_2020]
know_test_idx = [pd.read_csv(path) for path in i_test_paths]

In [10]:
know_test = [pd.read_csv(path) for path in TEST_PATHs]
for i in range(4):
    know_test[i].index = know_test_idx[i]['idx']

know_test[0].head() # 2017년도 test 샘플

,티칭,통관,급증,행정,압착,모니터,조종사,발성,우편물,촬영,...,연구기법,공장,통계,어려움,기기사용법,치과의사,부서,컨베이어,신소재,물량
idx,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
know_test[1].head()

,종사자교육,통관,전기치료기,자격연수,행정,쵸크,절연장갑,살대,수술도구,조종사,...,쇠톱,섬유기술사,MTS,통계,바이오에너지,조명배치도,치과의사,처리기기,컨베이어,물량
idx,,,,,,,,,,,,,,,,,,,,,
9486,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9488,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 테스트셋 추출 및 학습

ID 값을 제외한 나머지 데이터를 이용하여 모델에 넣어 추론합니다.

In [12]:
test_data = {}
for year, df in zip(years, know_test):
    print(year)
    train_columns = train_data[year]['X'].columns
    # print(train_columns)
    test_data[year] =  {'X': df[train_columns]}

2017
2018
2019
2020

In [13]:
for year in years:
    print(year)
    print(f"train: {train_data[year]['X'].shape} test: {test_data[year]['X'].shape}")

2017
train: (9486, 1952) test: (9486, 1952)
2018
train: (9072, 2437) test: (9069, 2437)
2019
train: (8555, 1853) test: (8554, 1853)
2020
train: (8122, 1791) test: (8122, 1791)

### ET로 예측

In [14]:
et_predicts = [] 

for year in tqdm(years):
    pred = et_models[year].predict(test_data[year]['X'])
    et_predicts.extend(pred)

100%|██████████| 4/4 [00:05<00:00,  1.35s/it]

# 제출

In [15]:
submission = pd.read_csv('../data_0103/sample_submission.csv') # sample submission 불러오기

In [16]:
submission['knowcode'] = et_predicts

submission.to_csv('../submission_files/et_smote_with_data_keywords.csv', index=False)